//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Logica.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosiblesClientes
    {
        public long Identificacion { get; set; }
        public string Primero_Nombre { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Primero_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Dirreccion { get; set; }
        public string Empresa { get; set; }
    }
}
