//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Logica.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int tareaCodigo { get; set; }
        public string tareaTitular { get; set; }
        public string tareaAsunto { get; set; }
        public string tareaFechaVencimiento { get; set; }
        public string tareaContacto { get; set; }
        public string tareaCuenta { get; set; }
        public int estadoCodigo { get; set; }
        public int prioridaCodigo { get; set; }
        public string tareaEnviarMensaje { get; set; }
        public string tareaRepetir { get; set; }
        public string tareaDescripcion { get; set; }
    
        public virtual EstadoTareas EstadoTareas { get; set; }
        public virtual Prioridad Prioridad { get; set; }
    }
}
