//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Logica.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string User { get; set; }
        public int ID { get; set; }
        public string descripcion { get; set; }
        public string password { get; set; }
        public string usaImagen { get; set; }
    }
}
